web:
  build: .
  ports:
    - "5000:5000"
  volumes:
    - ./app:/app
  links:
    - db
    - memcached
  command: /bin/bash -c /scripts/run.sh
  volumes:
    - /data/resizephoto/images:/app/images

db:
  image: mongo:3.0.15
  volumes:
    - /data/resizephoto/data/db:/data/db

memcached:
  image: memcached:1.5.3